version: '3.8'

services:
  app:
    build: .
    container_name: booking_app
    ports:
      - "8080:8080"
    command: [ "/app/booking-cli", "server" ]
    depends_on:
      - postgres
      - jaeger
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=booking-service
      - REDIS_ADDR=booking_redis:6379
      - DATABASE_URL=postgres://user:password@postgres:5432/booking?sslmode=disable
      - GIN_MODE=release
      - APP_ENV=production

  postgres:
    image: postgres:15-alpine
    container_name: booking_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
    command: -c 'max_connections=1000'

  redis:
    image: redis:7-alpine
    container_name: booking_redis
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: booking_prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: booking_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: booking_jaeger
    ports:
      - "16686:16686" # Web UI
      - "14268:14268" # Collector
      - "14250:14250" # GRPC
      - "4317:4317" # OTLP GRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  redis_data:
