global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'booking-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080', 'app:8080']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
